pipeline:
  notify:
    image: drillster/drone-email
    recipients_only: true
    secrets: [host, username, password, from, recipients]
  docker:
    image: plugins/docker
    repo: panchem/gfile
    tags: latest
    secrets: [docker_username, docker_password]
